---
title: "Model Building"
output: pdf_document
---

# Prepare data for modeling
```{r warning=FALSE, message = FALSE}
library(glmnet)

data <- read.csv("data/data_clean.csv") |>
  data.frame() 

data$UnablePregnant <- ifelse(data$UnablePregnant == "Yes", 1,
                              ifelse(data$UnablePregnant == "No", 0, NA))

X <- model.matrix(UnablePregnant ~ SEQN + Age + Race + Age_FirstPeriod +
                  RegularPeriod_12m + Age_LastPeriod + MCNP + MCOP +
                  MECPP + MBP + MCPP + MEP + MEHHP + MEHP +
                  MIBP + MEOHP + MBZP,
                  data = data)
X <- X[, -1]

y <- data$UnablePregnant

```

# All poisson regressions
```{r}
# Fit Poisson regression
fit_pois <- glm.fit(
  x = X,
  y = y,
  family = poisson(link = "log")
)

# Coefficients (log scale)
fit_pois$coefficients

# Risk ratios
exp(fit_pois$coefficients)
```

# All logit regressions
```{r}
fit_logit <- glm(y ~ X, family = binomial(link = "logit"))

summary(fit_logit)
```

# First/last period vs. MEP
```{r}
fit_lm <- lm(Age_FirstPeriod ~ MEP, data = data)
summary(fit_lm)

fit_lm <- lm(Age_LastPeriod ~ MEP, data = data)
summary(fit_lm)

fit_logit <- glm(UnablePregnant ~ MEP, data = data, family = binomial(link = "logit"))

summary(fit_logit)
```

# First/last period vs. MBZP
```{r}
fit_lm <- lm(Age_FirstPeriod ~ MBZP, data = data)
summary(fit_lm)

fit_lm <- lm(Age_LastPeriod ~ MBZP, data = data)
summary(fit_lm)

fit_logit <- glm(UnablePregnant ~ MBZP, data = data, family = binomial(link = "logit"))

summary(fit_logit)
```

# MCPP vs. last period
```{r}
fit_lm <- lm(Age_LastPeriod ~ MCPP, data = data)
summary(fit_lm)

fit_logit <- glm(UnablePregnant ~ MCPP, data = data, family = binomial(link = "logit"))

summary(fit_logit)

```

