---
title: "model_building_mixtures"
output:
  word_document: default
  html_document: default
  pdf_document: default
date: "2026-03-23"
---

```{r setup, include=FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(lubridate)
library(janitor)
library(ggplot2)
library(ggcorrplot)
library(ggfortify)
library(gridExtra)
library(factoextra)
library(psych)
library(GPArotation)
library(ggrepel)
library(pals)
library(GGally)
library(dendextend)
library(ggdendro)
library(reshape2)
library(forcats)
library(here)
```
Step 0 Preparing data 
```{r}
data <- read.csv("data/data_clean.csv") |>
  data.frame() 

#creating binary data 
data$UnablePregnant <- ifelse(data$UnablePregnant == "Yes", 1,
                              ifelse(data$UnablePregnant == "No", 0, NA))

data$RegularPeriod_12m <- ifelse(data$RegularPeriod_12m == "Yes", 1,
                              ifelse(data$RegularPeriod_12m == "No", 0, NA))

phthalates=data %>%
  select(-SEQN, -Race, -Age_FirstPeriod, -RegularPeriod_12m, -Age_LastPeriod, -UnablePregnant, -Year) %>%
  filter(Age <= 50)

demo = data %>%
  select(Race, Age, Age_FirstPeriod, RegularPeriod_12m, Age_LastPeriod, UnablePregnant, Year) %>%
  filter(Age <=50)

phthalates=phthalates %>%
  select(-Age)


phthalates_log <- log(phthalates)
as.numeric(unlist(phthalates_log))
phthalates_scaled <- scale(phthalates_log)
```
Step 1: PCA Analysis 
```{r}
ggcorr(phthalates_scaled)

pca.constituent <- prcomp(phthalates_scaled, scale.=TRUE)
summary(pca.constituent)

# creating eigenvalues
eigenvalues.v <- pca.constituent$sdev^2

perc_variance.v <- eigenvalues.v/sum(eigenvalues.v)
perc_variance.v <- round(100*perc_variance.v,1)

cumulative_perc_var.v <- cumsum(perc_variance.v)

eigenvalues.constituent <- data.frame(
PC = seq_along(eigenvalues.v),
Eigenvalue = eigenvalues.v,
Variance = perc_variance.v,
Cumulative = cumulative_perc_var.v)

eigenvalues.constituent

fviz_eig(pca.constituent)

loadings.constituent <- as.data.frame.matrix(pca.constituent$rotation)
loadings.constituent$Constituent <- rownames(loadings.constituent)

loadings.long <- loadings.constituent %>%
  pivot_longer(-Constituent, names_to="PC", values_to="Loading")

loadings.long %>%
  filter(PC %in% c("PC1","PC2")) %>%
  ggplot(aes(Constituent, Loading)) +
  geom_col() +
  facet_wrap(~PC) +
  theme_bw()

scores.constituent <- as.data.frame(pca.constituent$x)

scores.constituent <- scores.constituent %>%
  select(PC1:PC7)

head(scores.constituent)

# Now associating PCA exposure categories with our selected health symptoms 
pca_scores <- as.data.frame(pca.constituent$x)
pca_scores_3 <- pca_scores[, 1:3]

merged_pca_df <- cbind(phthalates_scaled, pca_scores_3)
merged_pca_df <- merged_pca_df %>%
  cbind(merged_pca_df, demo)

glimpse(merged_pca_df)

#Age at menarche
lm_menarche_pca <- lm(Age_FirstPeriod ~ PC1 + PC2 + PC3 + Race + Age + Year, 
                                data = merged_pca_df)
summary(lm_menarche_pca)

#Regular period 
glm_regular_period_pca <- glm(RegularPeriod_12m ~ PC1 + PC2 + PC3 + Race + Age + Year, 
                                data = merged_pca_df, family = binomial)
summary(glm_regular_period_pca)

#Trouble getting pregnant
glm_unable_pregnant <- glm(UnablePregnant ~ PC1 + PC2 + PC3 + Race + Age + Year, 
                                data = merged_pca_df, family = binomial)
summary(glm_unable_pregnant)


```
Step 2: Factor Analysis 
```{r}
fa_3.oblique <- fa(
  phthalates_scaled,
  nfactors = 3,
  rotate = "promax",
  scores = "regression",
  fm = "ml")

fa_3.oblique
print(fa_3.oblique$loadings, cutoff = 0.3)

#factor scores
scores.efa <- data.frame(fa_3.oblique$scores)
head(scores.efa)
```

## Now taking factor group membership and seeing how its associated with reproductive health outcomes by running regression models 
```{r}
#renaming groups
scores <- as.data.frame(fa_3.oblique$scores)
colnames(scores) <- c("F1", "F2", "F3")

#merge with the main df
merged_factor_df <- cbind(phthalates_scaled, scores)
head(merged_factor_df)

#merging back with data
merged_factor_df <- merged_factor_df %>%
  cbind(phthalates_scaled, demo)

#linear regression for age of menarche
model_menarche <- lm(Age_FirstPeriod ~ F1 + F2 + F3 + Race + Age + Year, data = merged_factor_df)
summary(model_menarche)

#logistic regression for trouble getting pregnant and regular periods 
#regular periods
model_regular <- glm(RegularPeriod_12m ~ F1 + F2 + F3 + Race + Age + Year, data = merged_factor_df,
                     family=binomial)
summary(model_regular)
exp(coef(model_regular))
confint(model_regular)

#trouble getting pregnant
model_pregnant <- glm(UnablePregnant ~ F1 + F2 + F3 + Race + Age + Year, data = merged_factor_df,
                      family = binomial)
summary(model_pregnant)
exp(coef(model_pregnant))
confint(model_pregnant)
```
