---
title: "Model Building- GLM Models"
output: pdf_document
---

# Load neccessary packages
```{r}
library(glmnet)
library(tidyverse)
library(broom)
library(patchwork)
```

# Load in dataset and use 0/1 for binary variables
```{r}
data <- read.csv("data/data_clean.csv") |>
  data.frame() 

data$UnablePregnant <- ifelse(data$UnablePregnant == "Yes", 1,
                              ifelse(data$UnablePregnant == "No", 0, NA))

data$RegularPeriod_12m <- ifelse(data$RegularPeriod_12m == "Yes", 1,
                              ifelse(data$RegularPeriod_12m == "No", 0, NA))
```

# Prepare data for modeling
```{r warning=FALSE, message = FALSE}
data =
  data |>
  mutate(Race = as.factor(Race))
         # RegularPeriod_12m = as.factor(RegularPeriod_12m),
         # UnablePregnant = as.factor(UnablePregnant),)
```

### Removing age 50+
```{r}
# Prepare data for modeling
data1 <- data |>
  filter(Age < 50) 
```

# Models with year and race
```{r}
glm_ability <- glm(UnablePregnant ~ MCNP + MCOP + MECPP + MBP + MCPP + MEP + MEHHP + MEHP + MIBP + MEOHP + MBZP + Age + Race + Year, data = data1, family = binomial)

glm_regularity <- glm(RegularPeriod_12m ~ MCNP + MCOP + MECPP + MBP + MCPP + MEP + MEHHP + MEHP + MIBP + MEOHP + MBZP + Age + Race + Year, data = data1, family = binomial)

glm_first_period <- glm(Age_FirstPeriod ~ MCNP + MCOP + MECPP + MBP + MCPP + MEP + MEHHP + MEHP + MIBP + MEOHP + MBZP + Age + Race + Year, data = data1, family = gaussian)
```

# Forest Plots
```{r}
# 95% CI
tidy_ability <- tidy(glm_ability, exponentiate = TRUE, conf.int = TRUE) |>
  filter(term != "(Intercept)")

tidy_regularity <- tidy(glm_regularity, exponentiate = TRUE, conf.int = TRUE) |>
  filter(term != "(Intercept)")

tidy_first <- tidy(glm_first_period, exponentiate = TRUE, conf.int = TRUE) |>
  filter(term != "(Intercept)")

# Forest Plots
ggplot(tidy_ability, aes(x = estimate, y = reorder(term, estimate))) +
  geom_point() +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.2) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  labs(
    x = "Odds Ratio (95% CI)",
    y = "Variables",
    title = "Odds Ratios for \nUnable to Become \nPregnant"
  ) +
  theme_minimal() -> ability1

ggplot(tidy_regularity, aes(x = estimate, y = reorder(term, estimate))) +
  geom_point() +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.2) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  labs(
    x = "Odds Ratio (95% CI)",
    y = "Variables",
    title = "Odds Ratios for\nRegular Menstrual Periods"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )-> regularity1

ggplot(tidy_first, aes(x = estimate, y = reorder(term, estimate))) +
  geom_point() +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.2) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  labs(
    x = "Odds Ratio (95% CI)",
    y = "Variables",
    title = "Odds Ratios for\nAge at First Period"
  ) +
  theme_minimal() -> first1
```

# All plots
```{r}
combined_plot = (ability1 + regularity1 + first1)
combined_plot

ggsave(
  filename = "glm_covariates.png",
  plot = combined_plot,
  width = 10.5,
  height = 5
)
```


# Models
```{r}
glm_ability <- glm(UnablePregnant ~ MCNP + MCOP + MECPP + MBP + MCPP + MEP + MEHHP + MEHP + MIBP + MEOHP + MBZP + Age, data = data1, family = binomial)

glm_regularity <- glm(RegularPeriod_12m ~ MCNP + MCOP + MECPP + MBP + MCPP + MEP + MEHHP + MEHP + MIBP + MEOHP + MBZP + Age, data = data1, family = binomial)

glm_first_period <- glm(Age_FirstPeriod ~ MCNP + MCOP + MECPP + MBP + MCPP + MEP + MEHHP + MEHP + MIBP + MEOHP + MBZP + Age, data = data1, family = gaussian)
```

# Forest Plots
```{r}
# 95% CI
tidy_ability <- tidy(glm_ability, exponentiate = TRUE, conf.int = TRUE) |>
  filter(term != "(Intercept)")

tidy_regularity <- tidy(glm_regularity, exponentiate = TRUE, conf.int = TRUE) |>
  filter(term != "(Intercept)")

tidy_first <- tidy(glm_first_period, exponentiate = TRUE, conf.int = TRUE) |>
  filter(term != "(Intercept)")

# Forest Plots
ggplot(tidy_ability, aes(x = estimate, y = reorder(term, estimate))) +
  geom_point() +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.2) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  labs(
    x = "Odds Ratio (95% CI)",
    y = "Variables",
    title = "Odds Ratios for \nUnable to Become Pregnant"
  ) +
  theme_minimal() -> ability1

ggplot(tidy_regularity, aes(x = estimate, y = reorder(term, estimate))) +
  geom_point() +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.2) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  labs(
    x = "Odds Ratio (95% CI)",
    y = "Variables",
    title = "Odds Ratios for\nRegular Menstrual Periods"
  ) +
  theme_minimal() -> regularity1

ggplot(tidy_first, aes(x = estimate, y = reorder(term, estimate))) +
  geom_point() +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0.2) +
  geom_vline(xintercept = 1, linetype = "dashed") +
  labs(
    x = "Odds Ratio (95% CI)",
    y = "Variables",
    title = "Odds Ratios for\n Age at First Period"
  ) +
  theme_minimal() -> first1
```

# All plots
```{r}
combined_plot = (ability1 + regularity1 + first1)
combined_plot

ggsave(
  filename = "glm_forest_plot.png",
  plot = combined_plot,
  width = 10,
  height = 4
)
```

